services:
  mysql:
    image: mysql:9.2.0
    container_name: anonymify-mysql
    working_dir: /application
    command: --max_allowed_packet=10000000000
    volumes:
      - .:/application
      - ./docker/data/mysql2:/var/lib/mysql:Z
      - ./database/config:/etc/mysql/mysql.conf.d:99-mariadb-tweaks.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anonym
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 13306:3306
  php:
    build: ./docker/php-fpm
    container_name: anonymify-php
    working_dir: /application
    environment:
      - APPLICATION_ENV=dev
      - PHP_IDE_CONFIG=serverName=_
      - APP_DEBUG=true
    volumes:
      - ./:/application
      - ./docker/php-fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini #Überschreibt die config für die Entwicklung
      - ./docker/php-fpm/config/development.ini:/usr/local/etc/php/php.ini #Überschreibt die config für die Entwicklung
    expose:
      - 9090
